### ISSUE TITLE
mapa mental Yadiria Olivia

### ISSUE THREAD

**Issue by yadiriaolivia** [SistemasTecTlaxiaco/actividad-4-mapa-mental-yadiriaolivia#1]
[Mapa mental Yadiria Olivia Miguel Aguilar... Fundamentos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-yadiriaolivia/files/9620589/Mapa.mental.Yadiria.Olivia.Miguel.Aguilar.Fundamentos.pdf)

**Comment by 11042002** [comment]
tu calificación es de 17.2%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
